version: '3'
services:
  app:
    build: ./app
    command: npm start
    environment:
      APP_WEATHER_API_KEY: $APP_WEATHER_API_KEY
    ports:
      - 5000:5000
  integration:
    build: ./integration
    command: npm test
    environment:
      APP_HOST: app
    depends_on:
      - app
